apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
      - name: hr-app
        image: ddivyadharshini28/cap-digital-bank:v1.1
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: 3000
        - name: MONGO_URI
          value: mongodb://rootuser:rootpassword@hr-mongo-service:27017/hr_system?authSource=admin
        - name: DB_NAME
          value: hr_system
        - name: MONGO_USERNAME
          value: rootuser
        - name: MONGO_PASSWORD
          value: rootpassword
        - name: DEFAULT_ADMIN_ID
          value: project
        - name: DEFAULT_ADMIN_PASSWORD
          value: project123
        - name: LOG_LEVEL
          value: info
---
apiVersion: v1
kind: Service
metadata:
  name: hr-app-service
spec:
  selector:
    app: hr-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
